### PR TITLE
Fixed int16 overflow

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
Fixed int16 overflow by using int64.

Removed the use of "file" because it is a built in python function.

updated docs to have consistent input arguments

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Thanks!  It will probably be a few days before I can review this.

**Comment by BebeSparkelSparkel** [comment]
Any chance to look at this yet?

**Comment by WarrenWeckesser** [comment]
William, thanks again for reporting the problem and submitting this pull request.  Sorry that "a few days" turned into a few weeks.

I decided to fix the problem in a slightly different way than you suggested here.  I've pushed my changes, so I'm closing this pull request.  I'll also likely incorporate some of the other cosmetic changes that you made, so thanks for those, too!

**Comment by BebeSparkelSparkel** [comment]
You're welcome for cosmetic changes
Thanks for getting around to it

**Pull request closed without merging**
